from django.db import models

# Create your models here.


class Model(models.Model):
    id = models.CharField(max_length=128, primary_key=True)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)


# just made this model to show foreign key in Email Model. This can be part of user_management service.
class User(Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=50)


class Email(Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    service_name = models.CharField(max_length=30)
    notification_type = models.CharField(max_length=20)
    notification_title = models.CharField(max_length=100)
    notification_description = models.CharField(max_length=500)
    to_email = models.CharField(max_length=30)
    channel_type = models.CharField(max_length=30)
    is_link_clicked = models.BooleanField(default=0)
    is_email_opened = models.BooleanField(default=0)
    is_bounced = models.BooleanField(default=0)
    is_email_sent = models.BooleanField(default=0)
    result = models.CharField(max_length=100)
    # assuming testing to done based on content generated by backed.
    a_b_test_method_type = models.CharField(max_length=30)
